spring:
  application:
    name: vcode-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vcode?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 369369
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
